# Support ThisKidCanCode's mission to keep coding education free for all students

# GitHub Sponsors (when available)
github: thiskidcancode

# Custom funding options
custom:
  - "https://opencollective.com/thiskidcancode"
