name: ⚙️ Backend API Work for Copilot Agent
description: Backend API development suitable for GitHub Copilot agents
title: "[BACKEND] "
labels: ["copilot-agent", "backend", "enhancement"]
assignees:
  - app/github-copilot
body:
  - type: markdown
    attributes:
      value: |
        ## 🤖 GitHub Copilot Agent Work
        This issue is designed for automated completion by GitHub Copilot agents.

        **🚨 CRITICAL: Branch Naming Convention - MUST FOLLOW EXACTLY**
        ```
        Branch Name Format: copilot/[ISSUE-NUMBER]-[brief-description]
        ```

        **⚠️ MANDATORY Git Flow Instructions:**
        1. **CREATE BRANCH FROM:** `develop` branch (NEVER from main)
        2. **BRANCH NAME:** `copilot/[THIS-ISSUE-NUMBER]-[description]` 
        3. **PR TARGET:** `develop` branch (for staging deployment)
        4. **FINAL MERGE:** After review, `develop` → `main` (production)

        **✅ Correct Example for this issue:**
        - Branch: `copilot/[ISSUE-NUMBER]-waitlist-api` 
        - PR: `copilot/[ISSUE-NUMBER]-waitlist-api` → `develop`

        **❌ Incorrect Examples:**
        - ~~`feature/add-waitlist-api`~~ (wrong prefix)
        - ~~`copilot/add-waitlist-api-integration`~~ (missing issue number)
        - ~~PR to `main`~~ (wrong target)

  - type: input
    id: api-name
    attributes:
      label: API Name
      description: Name of the API or service to create
      placeholder: e.g. Student Analytics API
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: 🎯 Objective
      description: Clear description of what this API should accomplish
      placeholder: Build API endpoints to track and analyze student learning patterns...
    validations:
      required: true

  - type: textarea
    id: endpoints
    attributes:
      label: 📖 API Endpoints
      description: List the specific endpoints to create
      value: |
        - `GET /api/analytics/student-progress?studentId={id}`
        - `POST /api/analytics/student-progress`
        - `GET /api/analytics/achievements?studentId={id}`
    validations:
      required: true

  - type: dropdown
    id: workspace
    attributes:
      label: 📁 Workspace
      description: Which workspace should this API be created in?
      options:
        - apprenticeship-platform
        - marketing-site
        - community-tools
    validations:
      required: true

  - type: textarea
    id: data-schema
    attributes:
      label: 📊 Data Schema
      description: TypeScript interfaces and data structures
      value: |
        ```typescript
        interface StudentProgress {
          studentId: string;
          lessonId: string;
          completedAt: Date;
          timeSpent: number;
          score?: number;
          attempts: number;
        }
        ```
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: 📋 Requirements
      description: Specific API requirements (use checkboxes)
      value: |
        - [ ] Implement proper error handling
        - [ ] Add input validation and sanitization
        - [ ] Include rate limiting
        - [ ] Follow REST API conventions
        - [ ] Add comprehensive logging
    validations:
      required: true

  - type: textarea
    id: security
    attributes:
      label: 🔐 Security Requirements
      description: Security considerations and requirements
      value: |
        - [ ] Validate all input parameters
        - [ ] Implement proper authentication
        - [ ] Add request rate limiting
        - [ ] Sanitize all user data
        - [ ] Include CORS configuration
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: 🧪 Acceptance Criteria
      description: Specific criteria for completion (use checkboxes)
      value: |
        - [ ] All endpoints return proper HTTP status codes
        - [ ] Input validation prevents malformed requests
        - [ ] Responses follow consistent JSON structure
        - [ ] Includes comprehensive error handling
        - [ ] Unit tests cover all endpoints
        - [ ] API documentation is complete
    validations:
      required: true

  - type: textarea
    id: file-locations
    attributes:
      label: 📁 File Locations
      description: Specify where files should be created
      value: |
        - API routes: `/[workspace]/src/pages/api/[feature]/`
        - Types: `/[workspace]/src/types/[feature].ts`
        - Tests: `/[workspace]/tests/api/[feature].test.ts`
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 🔄 Final Reminder: Git Workflow

        **When you start working on this issue:**

        1. **Check issue number:** This is issue #[ISSUE-NUMBER]
        2. **Create branch:** `git checkout develop && git pull && git checkout -b copilot/[ISSUE-NUMBER]-[description]`
        3. **Work on code:** Follow all requirements above
        4. **Create PR:** Target `develop` branch, NOT `main`
        5. **Branch name MUST include issue number:** `copilot/[ISSUE-NUMBER]-something`

        **❗ If branch name doesn't follow `copilot/[ISSUE-NUMBER]-description` format, PR will be rejected.**
